name: CI

on:
  push:
  pull_request:

jobs:
  rust:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Format
        run: cargo fmt --check

      - name: Check
        run: cargo check

      - name: Clippy
        run: cargo clippy --all-targets --workspace --exclude firmware -- -D warnings

      - name: Test app core
        run: cargo test -p app-core

      - name: Check firmware
        run: cargo check -p firmware --target riscv32imac-unknown-none-elf --release
